//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class account_credential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account_credential()
        {
            this.login_sessions = new HashSet<login_sessions>();
        }
    
        public string Id { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Please use a valid email address.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Username is required.")]
        [RegularExpression("^(?=[a-zA-Z0-9._]{6,18}$)(?!.*[_.]{2})[^_.].*[^_.]$", ErrorMessage = "Invalid username.")]
        [MinLength(8, ErrorMessage = "Username must be 8-16 characters.")]
        [MaxLength(16, ErrorMessage = "Username must be 8-16 characters.")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [MinLength(16, ErrorMessage = "Password must be 8-128 characters.")]
        [MaxLength(128, ErrorMessage = "Password must be 8-128 characters.")]
        public string Password { get; set; }

        public int AccountTypeId { get; set; }
        public bool IsArchived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login_sessions> login_sessions { get; set; }
    }
}
