//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class clinic_contact
    {
        public string Id { get; set; }
        public string ClinicId { get; set; }

        [Required]
        [RegularExpression(@"^(09|\+639|639|9)\d{9}$", ErrorMessage = "Please use a valid phone number.")]
        public string Contact { get; set; }

        public virtual clinic_profile clinic_profile { get; set; }
    }
}
