//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clinic_profile()
        {
            this.clinic_contact = new HashSet<clinic_contact>();
            this.clinic_review = new HashSet<clinic_review>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string VetFirstName { get; set; }
        public string VetMiddleName { get; set; }
        public string VetLastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinic_contact> clinic_contact { get; set; }
        public virtual clinic_address clinic_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinic_review> clinic_review { get; set; }
    }
}
