//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic_review
    {
        public string Id { get; set; }
        public string ClinicId { get; set; }
        public Nullable<double> Rating { get; set; }
        public string ReviewerId { get; set; }
        public string ReviewContent { get; set; }
        public System.DateTime ReviewCreationDate { get; set; }
    
        public virtual clinic_profile clinic_profile { get; set; }
        public virtual pet_profile pet_profile { get; set; }
    }
}
