//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_sessions
    {
        public string AccountId { get; set; }
        public string Token { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public string Id { get; set; }
    
        public virtual account_credential account_credential { get; set; }
    }
}
