//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MainDBEntities : DbContext
    {
        public MainDBEntities()
            : base("name=MainDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_credential> account_credential { get; set; }
        public virtual DbSet<account_type> account_type { get; set; }
        public virtual DbSet<clinic_address> clinic_address { get; set; }
        public virtual DbSet<clinic_contact> clinic_contact { get; set; }
        public virtual DbSet<clinic_profile> clinic_profile { get; set; }
        public virtual DbSet<clinic_review> clinic_review { get; set; }
        public virtual DbSet<following> followings { get; set; }
        public virtual DbSet<login_sessions> login_sessions { get; set; }
        public virtual DbSet<owner_address> owner_address { get; set; }
        public virtual DbSet<owner_contact> owner_contact { get; set; }
        public virtual DbSet<owner_profile> owner_profile { get; set; }
        public virtual DbSet<pet_breeds> pet_breeds { get; set; }
        public virtual DbSet<pet_category> pet_category { get; set; }
        public virtual DbSet<pet_profile> pet_profile { get; set; }
        public virtual DbSet<profile_post> profile_post { get; set; }
        public virtual DbSet<profile_post_comment> profile_post_comment { get; set; }
        public virtual DbSet<profile_post_like> profile_post_like { get; set; }
        public virtual DbSet<ClinicProfile> ClinicProfiles { get; set; }
        public virtual DbSet<OwnerProfile> OwnerProfiles { get; set; }
        public virtual DbSet<PetProfile> PetProfiles { get; set; }
    
        public virtual ObjectResult<Haversine_Result> Haversine(Nullable<decimal> custLat, Nullable<decimal> custLng)
        {
            var custLatParameter = custLat.HasValue ?
                new ObjectParameter("custLat", custLat) :
                new ObjectParameter("custLat", typeof(decimal));
    
            var custLngParameter = custLng.HasValue ?
                new ObjectParameter("custLng", custLng) :
                new ObjectParameter("custLng", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Haversine_Result>("Haversine", custLatParameter, custLngParameter);
        }
    }
}
