//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner_address
    {
        public string Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Barangay { get; set; }
        public string Line { get; set; }
    
        public virtual owner_profile owner_profile { get; set; }
    }
}
