//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pet_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pet_profile()
        {
            this.clinic_review = new HashSet<clinic_review>();
            this.profile_post_comment = new HashSet<profile_post_comment>();
            this.profile_post = new HashSet<profile_post>();
        }
    
        public string Id { get; set; }
        public string OwnerId { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z0-9\s#'.,\-()]*$", ErrorMessage = @"Acceptable characters are: a-z A-Z 0-9#'.,\-()")]
        [MaxLength(35, ErrorMessage = "Pet name must be less than 35 characters.")]
        public string Name { get; set; }

        [Required]
        [Range(typeof(DateTime), "1/1/1960", "1/1/2030", ErrorMessage = "Invalid Date")]
        public System.DateTime Birthdate { get; set; }

        [Required]
        public int CategoryId { get; set; }

        [Required]
        public Nullable<int> BreedId { get; set; }

        [Required]
        [RegularExpression(@"[a-zA-Z\s\p{P}]*", ErrorMessage = "Please use english characters or commas")]
        public string Color { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinic_review> clinic_review { get; set; }
        public virtual owner_profile owner_profile { get; set; }
        public virtual pet_breeds pet_breeds { get; set; }
        public virtual pet_category pet_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profile_post_comment> profile_post_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profile_post> profile_post { get; set; }
    }
}
