//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet_profile
    {
        public string Id { get; set; }
        public string OwnerId { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthdate { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> BreedId { get; set; }
        public string Color { get; set; }
    
        public virtual owner_profile owner_profile { get; set; }
    }
}
