//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummaryReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet_breeds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pet_breeds()
        {
            this.pet_profile = new HashSet<pet_profile>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Breed { get; set; }
    
        public virtual pet_category pet_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pet_profile> pet_profile { get; set; }
    }
}
